### ISSUE TITLE
replace "Temporary re-implementation of 'load_env_azure_settings'"

### ISSUE THREAD

**Issue by timabell** [DFE-Digital/publish-teacher-training#1049]
### What did you do? (steps to reproduce)

Read some code

### What happened? (actual results)

Found a todo

https://github.com/DFE-Digital/manage-courses-backend/blob/13050703093717d45f3733cd6446325547516751/lib/mcb.rb#L344-L349 ---- https://github.com/DFE-Digital/teacher-training-api/blob/master/lib/mcb.rb#L367

### What should have happened? (expected results)

Lack of todo

**Comment by defong** [comment]
stale
