### ISSUE TITLE
Update documentation to show possible values for course_length in CourseAttributes

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/publish-teacher-training#1687]
Documentation currently states: `Text describing how long the course runs`, but looking at Find, appears that it can be either `OneYear`, `TwoYears` or a string:

https://github.com/DFE-Digital/find-teacher-training/blob/94de46eea7ddeec2daca2e4944b9bf4582d25304/app/decorators/course_decorator.rb#L85-L94

Documentation would be more helpful if this information was provided.

**Comment by defong** [comment]
stale
