### ISSUE TITLE
Enable filtering of courses by `findable` and `running`

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/publish-teacher-training#1694]
### What did you do? (steps to reproduce)

I am trying to get a list of `running` and `findable` courses to show in the Find prototype.

### What happened? (actual results)

There’s currently [no filter options available](https://api.publish-teacher-training-courses.service.gov.uk/api-reference.html#schema-filter) for getting back a list of running and findable courses.

### What should have happened? (expected results)

Include ability to filter by `running` and `findable`: 

https://api.publish-teacher-training-courses.service.gov.uk/api/public/v1/recruitment_cycles/2021/courses/?page=1&per_page=20&filter[findable]=true&filter[running]=true

**Comment by defong** [comment]
Hey there, @paulrobertlloyd 

@TobyRet has done half of the job
https://github.com/DFE-Digital/teacher-training-api/pull/1726

The other half I'm going to leave to @gpeng discretions.

**Comment by defong** [comment]
stale
