### ISSUE TITLE
Include meta object in provider courses response

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/publish-teacher-training#1733]
For a list of all courses (https://api.publish-teacher-training-courses.service.gov.uk/api/public/v1/recruitment_cycles/2021/courses), a meta object is returned that includes the total number of results:

```json
"meta": {
  "count": 18048
}
```

For a list of all courses from a provider (https://api.publish-teacher-training-courses.service.gov.uk/api/public/v1/recruitment_cycles/2021/providers/1L9/courses), no meta object is included, so it’s not possible to get the total number of courses from a provider.

**Comment by defong** [comment]
stale
