### ISSUE TITLE
Course status is overly-complicated and multi-dimensional

### ISSUE THREAD

**Issue by misaka** [DFE-Digital/publish-teacher-training#895]
Currently the status for a `Course` is hard to reason through as it's multi-dimensional (relies on [`content_status`](https://github.com/DFE-Digital/manage-courses-backend/blob/78058fe033613f545fdeef667ec90f5d65649488/app/models/course.rb#L307-L312) and [`ucas_status`](https://github.com/DFE-Digital/manage-courses-backend/blob/78058fe033613f545fdeef667ec90f5d65649488/app/models/course.rb#L285-L305), which in turn are dynamically calculated from multiple other sources). This means to reason what state a course is, and what it means, we have to hold way too much context in our head, and makes working on anything related to a course's status (e.g. the [displayed status in the courses table](https://bat-design-history.herokuapp.com/publish-teacher-training/migrating-publish-statuses)).

**Comment by misaka** [comment]
One potential fix for this is to add a state machine to the course model, and to use that to define the states a course can be in, with all the appropriate transitions, on-transition actions, guards, state validations, etc.

**Comment by fofr** [comment]
From 2020-2021, ucas_status can be derived from content_status.

**Comment by fofr** [comment]
The idea was that a course status new/draft/published/withdrawn should cascade to the UCAS status – running/not running/suspended – which in turn cascades to the sites attached to the course. The exception being a site that's attached but removed from a course, which must independently show as suspended.
